on: push
env:
  tenancy: 'ocid1.tenancy.oc1..aaaaaaaakatveh74zmu3624wgdcs2zcud5emtkpeqrv3b4xnc6gwlw52nvtq'
  user: 'ocid1.user.oc1..aaaaaaaagu3ghstfw5oynuruw6hudunbjsmroyko6ue6lnshxumwskv2ipjq'
  regionId: 'ap-seoul-1'
  fingerprint: ${{ secrets.FINGER_PRINT }}
  privateKey: ${{ secrets.PRIVATE_KEY }}
jobs:
  common:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: common
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm install
      - run: npm test
  logging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: logging
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm install
      - run: npm test
